name = "mail-2"
compatibility_date = "2024-06-16"
compatibility_flags = ["nodejs_compat"]


[[r2_buckets]]
binding = "R2_BUCKET_NAME"
bucket_name = "service-app"


[observability]
enabled = true
head_sampling_rate = 1 
